enum AnimationActionEnums {
    ANIMATION_ACTION_CUT_TREE,
    ANIMATION_ACTION_PLAY_CUT_WOOD_SOUND,
    ANIMATION_ACTION_PLAY_FOOTSTEPS,
    ANIMATION_ACTION_ATTACK_ENEMY,
    ANIMATION_ACTION_PLAY_SWORD_SOUND,
    ANIMATION_ACTION_PLAY_BUILD_SOUND,
    ANIMATION_ACTION_BUILD_HOUSE_INTERMEDIATE,
    ANIMATION_ACTION_BUILD_HOUSE,
    ANIMATION_ACTION_BUILD_TOWER_INTERMEDIATE,
    ANIMATION_ACTION_BUILD_TOWER,
    ANIMATION_ACTION_REMOVE_FROM_WORLD,
};

enum SelectedMoveType {
	MOVE_TYPE_NONE,
	MOVE_TYPE_CHOP,
	MOVE_TYPE_BUILD_HOUSE,
	MOVE_TYPE_BUILD_TOWER,
};

enum MovementActionEnums { //NOTE: When player clicks on an action but needs to walk there first to perform it
    MOVEMENT_ACTION_NONE = 0,
    MOVEMENT_ACTION_CUT_TREE,
    MOVEMENT_ACTION_FIGHT_ENEMY,
    MOVEMENT_ACTION_BUILD_HOUSE, //NOTE: For Peaseants building structures
    MOVEMENT_ACTION_BUILD_TOWER, //NOTE: For Peaseants building structures
    MOVEMENT_ACTION_SHOOT, //NOTE: NOTE: for archers shooting enemies
};

/////// UI types used by the Game UI overlay //////////

enum GameChoiceUi {
    GAME_CHOICE_UI_NONE,
    GAME_CHOICE_UI_PEASANT,
	GAME_CHOICE_UI_PEASANT_BUILD,
};

enum UiButtonType {
    UI_BUTTON_NONE,
    UI_BUTTON_NEXT_TURN,
    UI_BUTTON_PEASEANT_ACTION_CHOP,
    UI_BUTTON_PEASEANT_ACTION_BUILD,
    UI_BUTTON_PEASEANT_ACTION_BUILD_HOUSE,
    UI_BUTTON_PEASEANT_ACTION_BUILD_TOWER,
};